config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "goals", to: "goals#index"
  post "save_goal", to: "goals#save_goal"
  
  get 'passkey/:character_name', to: 'home#passkey', as: 'passkey'
  post "passkey/:character_name", to: "home#submit_passkey"

  get 'goals/:character_name/tracking', to: 'goals/tracking#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :goals
end

app/controllers/Goals/tracking_controller.rb
module Goals
  class TrackingController < ApplicationController
    def index
      @character_name = params[:character_name]

      @daily_goals = Array.new(5) do
        (1..365).map { |key| [key, rand(0..4) * rand(0..1)] }.to_h
      end

      @goal_names = ['Exercise', 'Meditation', 'Reading', 'Coding', 'Writing']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    names = ["Chris", "Jake", "Caleb", "Jimmy", "Brycen"] # TODO: Grab this from configuration.
    @goals = []

    names.each do |name|
      member = User.find_or_initialize_by(first_name: name)
      member.save! unless member.persisted?

      goal = Goal.find_or_initialize_by(user: member)
      goal.save! unless goal.persisted?

      @goals << goal
    end
  end

  def save_goal
    member = User.find_or_initialize_by(first_name: params[:member])
    goal = Goal.find_or_initialize_by(user: member)
    
    goal.update!(content: params[:goal])

    flash[:notice] = "Your goal was saved successfully!"
    redirect_to goals_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def passkey
    @character_name = params[:character_name]
  end
  
  def submit_passkey
    user = User.find_by(first_name: params[:character_name])
    if user.passkey == params[:passkey]
      session[:character_name] = params[:character_name]
      redirect_to goals_path
    else
      flash[:error] = "The entered passkey is incorrect!"
      redirect_to passkey_path
    end
  end
end

app/helpers/Goals/tracking_helper.rb
module Goals
  module TrackingHelper
    def get_day_progess_value(week_index, day_index, hash)
      day = (week_index * 7 + day_index) - 1
      return "hidden" if day <= 0 || day > 365

      hash[day]
    end

    def get_tooltip_text(week_index, day_index, progress_index)
      day_number = (week_index * 7 + day_index) - 1

      start_date = Date.new(2025, 1, 1)
      current_date = start_date + (day_number - 1)

      day_suffix = case current_date.day
                  when 1, 21, 31 then 'st'
                  when 2, 22 then 'nd'
                  when 3, 23 then 'rd'
                  else 'th'
                  end
      formatted_date = "#{current_date.strftime('%B')} #{current_date.day}#{day_suffix}, #{current_date.year}"

      "#{formatted_date}: #{progress_index * 25}%"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/goals/index.html.erb
<div class="container">
  <h1>Goals for 2025 🎉</h1>

  <div class="goals">

    <% @goals.each do |goal| %>
      <div class="goal">
        <h2><%= goal.user.first_name %>'s Goals</h2>
        <%= form_with url: save_goal_path, method: :post, local: true do |form| %>
          <%= form.hidden_field :member, value: goal.user.first_name %>
          <%= form.text_area :goal, value: goal.content, placeholder: "Write your goal here...", rows: 5, disabled: goal.user.first_name != session[:character_name] %>
          <% if goal.user.first_name == session[:character_name] %>
            <%= form.submit "Save" %>
          <% end %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/goals/tracking/index.html.erb
<div class="goal-tracking-container">
    <div class="header">
        <div class="title">
            Goal Tracker
        </div>
    </div>
    <div class="content" data-controller="tracking">
        <% @daily_goals.each.with_index do |goal, i|%>
            <div 
                class="daily-goal-updater" 
                data-action="click->tracking#toggleUpdateProgress" 
                data-index="<%= i %>">
                    Update Daily Progress <span class="arrow">▼</span>
            </div>
            <div class="daily-goal-container">
                <span class="goal-title"><%= @goal_names[i] %></span>
                <div class="grid">
                    <% (0..52).each do |week| %>
                        <div class="week">
                            <% (1..7).each do |day| %>
                                <% progress_value = get_day_progess_value(week, day, goal) %>
                                <div 
                                    class="day" 
                                    goal-progress="<%= progress_value %>" 
                                    title="<%= get_tooltip_text(week, day, progress_value) %>">
                                </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
                <div class="goal-legend">
                    Less
                    <div class="day" goal-progress="0"></div>
                    <div class="day" goal-progress="1"></div>
                    <div class="day" goal-progress="2"></div>
                    <div class="day" goal-progress="3"></div>
                    <div class="day" goal-progress="4"></div>
                    More
                </div>
            </div>
            <div class="update-progress-container hidden" data-tracking-target="updateProgress">
                <%= Date.today.strftime("%A, %B %d, %Y") %>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div class="home-body">
  <div class="home-header">
    Choose your character:
  </div>
  <div class="home-container">
    <%= link_to passkey_path(character_name: 'Chris'), class: 'character-card' do %>
    <img src="assets/chris-character.jpg" alt="Chris">
    <% end %>
    <%= link_to passkey_path(character_name: 'Jake'), class: 'character-card' do %>
      <img src="assets/jake-character.jpg" alt="Jake">
    <% end %>
    <%= link_to passkey_path(character_name: 'Caleb'), class: 'character-card' do %>
      <img src="assets/caleb-character.jpg" alt="Caleb">
    <% end %>
    <%= link_to passkey_path(character_name: 'Jimmy'), class: 'character-card' do %>
      <img src="assets/jimmy-character.jpg" alt="Jimmy">
    <% end %>
    <%= link_to passkey_path(character_name: 'Brycen'), class: 'character-card' do %>
      <img src="assets/brycen-character.jpg" alt="Brycen">
    <% end %>
</div>

app/views/home/passkey.html.erb
<div class="passkey-container">
  <div class="passkey-title">
    Enter the passkey for <%= @character_name.capitalize %>
  </div>
  <form action="#" method="post">
    <input type="password" id="passkey" name="passkey" required>
    <button type="submit">Submit</button>
  </form>

  <%= link_to 'Cancel', root_path, class: 'cancel-button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>2025 Goals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'celebration.png' %>

    <%= stylesheet_link_tag 'goals', media: 'all' %>
    <%= stylesheet_link_tag 'tracking', media: 'all' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="flash error"><%= flash[:error] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>